import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderSection from "@/components/layout/Header";
import { Provider } from "@/context/contextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit_Log - Workout Library | Piyas Ahmed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full l bg-[#0B0B0F] text-white">
        <Provider>
          <header className="border-b">
            <HeaderSection />
          </header>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
